version: '3.8'
services:
  postgres:
    container_name: "postgres-albion-analysis"
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
