"""create tables

Revision ID: 2282cd38c60d
Revises:
Create Date: 2023-04-23 16:35:14.349807

"""
from alembic import op
import sqlalchemy as sa
from devtools.providers.database.types import GUUID


# revision identifiers, used by Alembic.
revision = '2282cd38c60d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('city', sa.Enum('CAERLEON', 'BRIDGEWATCH', 'MARTLOCK', 'LYMHURST', 'FORT_STERLING', 'THETFORD', name='citiesenum'), nullable=True),
    sa.Column('last_sell_price', sa.Integer(), nullable=True),
    sa.Column('last_buy_price', sa.Integer(), nullable=True),
    sa.Column('last_price_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_city'), 'items', ['city'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_last_buy_price'), 'items', ['last_buy_price'], unique=False)
    op.create_index(op.f('ix_items_last_price_date'), 'items', ['last_price_date'], unique=False)
    op.create_index(op.f('ix_items_last_sell_price'), 'items', ['last_sell_price'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_table('items_history',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('city', sa.Enum('CAERLEON', 'BRIDGEWATCH', 'MARTLOCK', 'LYMHURST', 'FORT_STERLING', 'THETFORD', name='citiesenum'), nullable=True),
    sa.Column('last_sell_price', sa.Integer(), nullable=True),
    sa.Column('last_buy_price', sa.Integer(), nullable=True),
    sa.Column('last_price_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_history_city'), 'items_history', ['city'], unique=False)
    op.create_index(op.f('ix_items_history_id'), 'items_history', ['id'], unique=False)
    op.create_index(op.f('ix_items_history_last_buy_price'), 'items_history', ['last_buy_price'], unique=False)
    op.create_index(op.f('ix_items_history_last_price_date'), 'items_history', ['last_price_date'], unique=False)
    op.create_index(op.f('ix_items_history_last_sell_price'), 'items_history', ['last_sell_price'], unique=False)
    op.create_index(op.f('ix_items_history_name'), 'items_history', ['name'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_stats_id'), 'player_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_stats_name'), 'player_stats', ['name'], unique=False)
    op.create_table('alchemy_stats',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('max_tier_enable', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'TIER_4', 'TIER_5', 'TIER_6', 'TIER_7', 'TIER_8', name='itemtier'), nullable=False),
    sa.Column('bonus_class_focus', sa.DECIMAL(), nullable=True),
    sa.Column('player_stats_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['player_stats_id'], ['player_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alchemy_stats_id'), 'alchemy_stats', ['id'], unique=False)
    op.create_index(op.f('ix_alchemy_stats_name'), 'alchemy_stats', ['name'], unique=False)
    op.create_table('animal_creation_stats',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('max_tier_enable', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'TIER_4', 'TIER_5', 'TIER_6', 'TIER_7', 'TIER_8', name='itemtier'), nullable=False),
    sa.Column('bonus_class_focus', sa.DECIMAL(), nullable=True),
    sa.Column('player_stats_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['player_stats_id'], ['player_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_creation_stats_id'), 'animal_creation_stats', ['id'], unique=False)
    op.create_index(op.f('ix_animal_creation_stats_name'), 'animal_creation_stats', ['name'], unique=False)
    op.create_table('combat_stats',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('max_tier_enable', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'TIER_4', 'TIER_5', 'TIER_6', 'TIER_7', 'TIER_8', name='itemtier'), nullable=False),
    sa.Column('bonus_class', sa.DECIMAL(), nullable=False),
    sa.Column('player_stats_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['player_stats_id'], ['player_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combat_stats_id'), 'combat_stats', ['id'], unique=False)
    op.create_index(op.f('ix_combat_stats_name'), 'combat_stats', ['name'], unique=False)
    op.create_table('crafting_stats',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('max_tier_enable', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'TIER_4', 'TIER_5', 'TIER_6', 'TIER_7', 'TIER_8', name='itemtier'), nullable=False),
    sa.Column('bonus_class_focus', sa.DECIMAL(), nullable=True),
    sa.Column('bonus_class_quality', sa.DECIMAL(), nullable=True),
    sa.Column('player_stats_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['player_stats_id'], ['player_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crafting_stats_id'), 'crafting_stats', ['id'], unique=False)
    op.create_index(op.f('ix_crafting_stats_name'), 'crafting_stats', ['name'], unique=False)
    op.create_table('harvester_stats',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('max_tier_enable', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'TIER_4', 'TIER_5', 'TIER_6', 'TIER_7', 'TIER_8', name='itemtier'), nullable=False),
    sa.Column('bonus_class_focus', sa.DECIMAL(), nullable=True),
    sa.Column('player_stats_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['player_stats_id'], ['player_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvester_stats_id'), 'harvester_stats', ['id'], unique=False)
    op.create_index(op.f('ix_harvester_stats_name'), 'harvester_stats', ['name'], unique=False)
    op.create_table('herbalist_stats',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('max_tier_enable', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'TIER_4', 'TIER_5', 'TIER_6', 'TIER_7', 'TIER_8', name='itemtier'), nullable=False),
    sa.Column('bonus_class_focus', sa.DECIMAL(), nullable=True),
    sa.Column('player_stats_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['player_stats_id'], ['player_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_herbalist_stats_id'), 'herbalist_stats', ['id'], unique=False)
    op.create_index(op.f('ix_herbalist_stats_name'), 'herbalist_stats', ['name'], unique=False)
    op.create_table('refining_stats',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('bonus_item_focus', sa.DECIMAL(), nullable=True),
    sa.Column('bonus_class_focus', sa.DECIMAL(), nullable=True),
    sa.Column('player_stats_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['player_stats_id'], ['player_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refining_stats_id'), 'refining_stats', ['id'], unique=False)
    op.create_index(op.f('ix_refining_stats_name'), 'refining_stats', ['name'], unique=False)
    op.create_table('sous_chef_stats',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('max_tier_enable', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'TIER_4', 'TIER_5', 'TIER_6', 'TIER_7', 'TIER_8', name='itemtier'), nullable=False),
    sa.Column('bonus_class_focus', sa.DECIMAL(), nullable=True),
    sa.Column('player_stats_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['player_stats_id'], ['player_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sous_chef_stats_id'), 'sous_chef_stats', ['id'], unique=False)
    op.create_index(op.f('ix_sous_chef_stats_name'), 'sous_chef_stats', ['name'], unique=False)
    op.create_table('alchemyst_specialist',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('bonus_item_focus', sa.DECIMAL(), nullable=True),
    sa.Column('bonus_class_focus', sa.DECIMAL(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('alchemy_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['alchemy_id'], ['alchemy_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alchemyst_specialist_id'), 'alchemyst_specialist', ['id'], unique=False)
    op.create_index(op.f('ix_alchemyst_specialist_name'), 'alchemyst_specialist', ['name'], unique=False)
    op.create_table('animal_creation_specialist',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('bonus_item_focus', sa.DECIMAL(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('animal_creation_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['animal_creation_id'], ['animal_creation_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_creation_specialist_id'), 'animal_creation_specialist', ['id'], unique=False)
    op.create_index(op.f('ix_animal_creation_specialist_name'), 'animal_creation_specialist', ['name'], unique=False)
    op.create_table('combat_specialist',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('bonus_item', sa.DECIMAL(), nullable=True),
    sa.Column('bonus_class', sa.DECIMAL(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('combat_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['combat_id'], ['combat_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combat_specialist_id'), 'combat_specialist', ['id'], unique=False)
    op.create_index(op.f('ix_combat_specialist_name'), 'combat_specialist', ['name'], unique=False)
    op.create_table('crafting_specialist',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('bonus_item_focus', sa.DECIMAL(), nullable=True),
    sa.Column('bonus_class_focus', sa.DECIMAL(), nullable=True),
    sa.Column('bonus_item_quality', sa.DECIMAL(), nullable=True),
    sa.Column('bonus_class_quality', sa.DECIMAL(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('crafting_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['crafting_id'], ['crafting_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crafting_specialist_id'), 'crafting_specialist', ['id'], unique=False)
    op.create_index(op.f('ix_crafting_specialist_name'), 'crafting_specialist', ['name'], unique=False)
    op.create_table('harvester_specialist',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('bonus_item_focus', sa.DECIMAL(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('harvester_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['harvester_id'], ['harvester_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvester_specialist_id'), 'harvester_specialist', ['id'], unique=False)
    op.create_index(op.f('ix_harvester_specialist_name'), 'harvester_specialist', ['name'], unique=False)
    op.create_table('herbalist_specialist',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('bonus_item_focus', sa.DECIMAL(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('herbalist_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['herbalist_id'], ['herbalist_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_herbalist_specialist_id'), 'herbalist_specialist', ['id'], unique=False)
    op.create_index(op.f('ix_herbalist_specialist_name'), 'herbalist_specialist', ['name'], unique=False)
    op.create_table('sous_chef_specialist',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('bonus_item_focus', sa.DECIMAL(), nullable=True),
    sa.Column('bonus_class_focus', sa.DECIMAL(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('sous_chef_id', GUUID(), nullable=True),
    sa.ForeignKeyConstraint(['sous_chef_id'], ['sous_chef_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sous_chef_specialist_id'), 'sous_chef_specialist', ['id'], unique=False)
    op.create_index(op.f('ix_sous_chef_specialist_name'), 'sous_chef_specialist', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sous_chef_specialist_name'), table_name='sous_chef_specialist')
    op.drop_index(op.f('ix_sous_chef_specialist_id'), table_name='sous_chef_specialist')
    op.drop_table('sous_chef_specialist')
    op.drop_index(op.f('ix_herbalist_specialist_name'), table_name='herbalist_specialist')
    op.drop_index(op.f('ix_herbalist_specialist_id'), table_name='herbalist_specialist')
    op.drop_table('herbalist_specialist')
    op.drop_index(op.f('ix_harvester_specialist_name'), table_name='harvester_specialist')
    op.drop_index(op.f('ix_harvester_specialist_id'), table_name='harvester_specialist')
    op.drop_table('harvester_specialist')
    op.drop_index(op.f('ix_crafting_specialist_name'), table_name='crafting_specialist')
    op.drop_index(op.f('ix_crafting_specialist_id'), table_name='crafting_specialist')
    op.drop_table('crafting_specialist')
    op.drop_index(op.f('ix_combat_specialist_name'), table_name='combat_specialist')
    op.drop_index(op.f('ix_combat_specialist_id'), table_name='combat_specialist')
    op.drop_table('combat_specialist')
    op.drop_index(op.f('ix_animal_creation_specialist_name'), table_name='animal_creation_specialist')
    op.drop_index(op.f('ix_animal_creation_specialist_id'), table_name='animal_creation_specialist')
    op.drop_table('animal_creation_specialist')
    op.drop_index(op.f('ix_alchemyst_specialist_name'), table_name='alchemyst_specialist')
    op.drop_index(op.f('ix_alchemyst_specialist_id'), table_name='alchemyst_specialist')
    op.drop_table('alchemyst_specialist')
    op.drop_index(op.f('ix_sous_chef_stats_name'), table_name='sous_chef_stats')
    op.drop_index(op.f('ix_sous_chef_stats_id'), table_name='sous_chef_stats')
    op.drop_table('sous_chef_stats')
    op.drop_index(op.f('ix_refining_stats_name'), table_name='refining_stats')
    op.drop_index(op.f('ix_refining_stats_id'), table_name='refining_stats')
    op.drop_table('refining_stats')
    op.drop_index(op.f('ix_herbalist_stats_name'), table_name='herbalist_stats')
    op.drop_index(op.f('ix_herbalist_stats_id'), table_name='herbalist_stats')
    op.drop_table('herbalist_stats')
    op.drop_index(op.f('ix_harvester_stats_name'), table_name='harvester_stats')
    op.drop_index(op.f('ix_harvester_stats_id'), table_name='harvester_stats')
    op.drop_table('harvester_stats')
    op.drop_index(op.f('ix_crafting_stats_name'), table_name='crafting_stats')
    op.drop_index(op.f('ix_crafting_stats_id'), table_name='crafting_stats')
    op.drop_table('crafting_stats')
    op.drop_index(op.f('ix_combat_stats_name'), table_name='combat_stats')
    op.drop_index(op.f('ix_combat_stats_id'), table_name='combat_stats')
    op.drop_table('combat_stats')
    op.drop_index(op.f('ix_animal_creation_stats_name'), table_name='animal_creation_stats')
    op.drop_index(op.f('ix_animal_creation_stats_id'), table_name='animal_creation_stats')
    op.drop_table('animal_creation_stats')
    op.drop_index(op.f('ix_alchemy_stats_name'), table_name='alchemy_stats')
    op.drop_index(op.f('ix_alchemy_stats_id'), table_name='alchemy_stats')
    op.drop_table('alchemy_stats')
    op.drop_index(op.f('ix_player_stats_name'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_items_history_name'), table_name='items_history')
    op.drop_index(op.f('ix_items_history_last_sell_price'), table_name='items_history')
    op.drop_index(op.f('ix_items_history_last_price_date'), table_name='items_history')
    op.drop_index(op.f('ix_items_history_last_buy_price'), table_name='items_history')
    op.drop_index(op.f('ix_items_history_id'), table_name='items_history')
    op.drop_index(op.f('ix_items_history_city'), table_name='items_history')
    op.drop_table('items_history')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_last_sell_price'), table_name='items')
    op.drop_index(op.f('ix_items_last_price_date'), table_name='items')
    op.drop_index(op.f('ix_items_last_buy_price'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_city'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
