"""create tables

Revision ID: 7bb9cbc685d3
Revises:
Create Date: 2023-02-21 15:34:00.979405

"""
from alembic import op
import sqlalchemy as sa
from devtools.providers.database.types import GUUID

# revision identifiers, used by Alembic.
revision = '7bb9cbc685d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('city', sa.Enum('CAERLEON', 'BRIDGEWATCH', 'MARTLOCK', 'LYMHURST', 'FORT_STERLING', 'THETFORD', name='citiesenum'), nullable=True),
    sa.Column('last_sell_price', sa.Integer(), nullable=True),
    sa.Column('last_buy_price', sa.Integer(), nullable=True),
    sa.Column('last_price_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_city'), 'items', ['city'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_last_buy_price'), 'items', ['last_buy_price'], unique=False)
    op.create_index(op.f('ix_items_last_price_date'), 'items', ['last_price_date'], unique=False)
    op.create_index(op.f('ix_items_last_sell_price'), 'items', ['last_sell_price'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_table('items_history',
    sa.Column('id', GUUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('city', sa.Enum('CAERLEON', 'BRIDGEWATCH', 'MARTLOCK', 'LYMHURST', 'FORT_STERLING', 'THETFORD', name='citiesenum'), nullable=True),
    sa.Column('last_sell_price', sa.Integer(), nullable=True),
    sa.Column('last_buy_price', sa.Integer(), nullable=True),
    sa.Column('last_price_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_history_city'), 'items_history', ['city'], unique=False)
    op.create_index(op.f('ix_items_history_id'), 'items_history', ['id'], unique=False)
    op.create_index(op.f('ix_items_history_last_buy_price'), 'items_history', ['last_buy_price'], unique=False)
    op.create_index(op.f('ix_items_history_last_price_date'), 'items_history', ['last_price_date'], unique=False)
    op.create_index(op.f('ix_items_history_last_sell_price'), 'items_history', ['last_sell_price'], unique=False)
    op.create_index(op.f('ix_items_history_name'), 'items_history', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_history_name'), table_name='items_history')
    op.drop_index(op.f('ix_items_history_last_sell_price'), table_name='items_history')
    op.drop_index(op.f('ix_items_history_last_price_date'), table_name='items_history')
    op.drop_index(op.f('ix_items_history_last_buy_price'), table_name='items_history')
    op.drop_index(op.f('ix_items_history_id'), table_name='items_history')
    op.drop_index(op.f('ix_items_history_city'), table_name='items_history')
    op.drop_table('items_history')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_last_sell_price'), table_name='items')
    op.drop_index(op.f('ix_items_last_price_date'), table_name='items')
    op.drop_index(op.f('ix_items_last_buy_price'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_city'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
